CREATE ROLE backend_dev LOGIN PASSWORD 'backend123';
CREATE ROLE bi_dev LOGIN PASSWORD 'bidev123';
CREATE ROLE data_engineer LOGIN PASSWORD 'dataeng123';

GRANT USAGE ON SCHEMA SALAM TO backend_dev, bi_dev, data_engineer;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SALAM TO backend_dev;
ALTER DEFAULT PRIVILIGES IN SCHEMA SALAM GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO backend_dev;

GRANT SELECT ON ALL TABLES IN SCHEMA SALAM TO bi_dev;
ALTER DEFAULT PRIVILIGES IN SCHEMA SALAM GRANT SELECT ON ALL TABLES TO bi_dev;

GRANT ALL PRIVILIGES ON ALL TABLES IN SCHEMA SALAM TO data_engineer;
GRANT CREATE, USAGE ON SCHEMA SALAM TO data_engineer;
ALTER DEFAULT PRIVILIGES IN SCHEMA SALAM GRANT ALL ON TABLES TO data_engineer;