  version: '3.5'

  services:
    postgres:
      container_name: postgres_Fauzan_Ramdhani
      image: postgres
      env_file: .env
      environment:
        POSTGRES_USER: ${POSTGRES_USER:-user}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
        PGDATA: /data/postgres
      volumes:
        - postgres:/data/postgres
      ports:
        - "22045:5432"
      networks:
        - postgres
      restart: unless-stopped
    
    pgadmin:
      container_name: pgadmin_Fauzan_Ramdhani
      image: dpage/pgadmin4
      env_file: .env
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
        - pgadmin:/var/lib/pgadmin

      ports:
        - "${PGADMIN_PORT:-44045}:80"
      networks:
        - postgres
      restart: unless-stopped

  networks:
    postgres:
      driver: bridge

  volumes:
      postgres:
      pgadmin:
